### ISSUE TITLE
Adicionar código inicial ao projeto

### ISSUE THREAD

**Issue by teles** [vivadecora/projeto-vaga-front-end-nao-fazer-fork#4]
Parte do código deve estar disponível no projeto.
Essa parte deve incluir o esqueleto html, css e javascript.

Deve ser decidido se devemos adicionar também:
* [ ] - Gerenciador de dependências;
* [ ] - Ui router / Ng router

**Comment by taciogt** [comment]
@teles, acho que isso pode ficar a critério do aplicante. Podemos avaliar as razões de ele ter escolhido determinada solução pra cada uma dessas questões.
